# Generated by Django 6.0 on 2025-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('department', models.CharField(max_length=200, verbose_name='Отдел')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('computer_number', models.CharField(max_length=100, verbose_name='Номер компьютера')),
                ('certificate_name', models.CharField(max_length=200, verbose_name='Сертификат')),
            ],
        ),
    ]
