# Generated by Django 6.0 on 2025-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('department', models.CharField(max_length=100, verbose_name='ОТДЕЛ')),
                ('expiry_date', models.DateField(verbose_name='ДАТА ОКОНЧАНИЯ')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('computer_number', models.CharField(max_length=50, verbose_name='Номер компьютера')),
                ('installed_certificate', models.CharField(max_length=100, verbose_name='Какой сертификат установлен')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalCertificate',
        ),
        migrations.DeleteModel(
            name='UserCertificate',
        ),
    ]
